# Generated by Django 4.1.6 on 2023-03-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='references',
            field=models.ManyToManyField(through='db.DiseaseReferenceLink', to='db.reference'),
        ),
    ]
