# Generated by Django 4.2.1 on 2023-05-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_remove_reference_diseases_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='icd_code',
            new_name='icode',
        ),
        migrations.RenameField(
            model_name='symptom',
            old_name='icd_code',
            new_name='icode',
        ),
        migrations.AlterField(
            model_name='cause',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diseasecauselink',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diseasedietlink',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diseasedruglink',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diseasepharmacotherapylink',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diseasepreventionlink',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diseaseregimentaltherapylink',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diseasesymptomlink',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diseasetreatmentprinciplelink',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drugpharmacotherapylink',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacotherapy',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prevention',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='regimentaltherapy',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='symptomregimentaltherapylink',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentprinciple',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='cause',
            table='causes',
        ),
        migrations.AlterModelTable(
            name='diet',
            table='diets',
        ),
        migrations.AlterModelTable(
            name='disease',
            table='diseases',
        ),
        migrations.AlterModelTable(
            name='diseasecauselink',
            table='disease_cause_link',
        ),
        migrations.AlterModelTable(
            name='diseasedietlink',
            table='disease_diet_link',
        ),
        migrations.AlterModelTable(
            name='diseasedruglink',
            table='disease_drug_link',
        ),
        migrations.AlterModelTable(
            name='diseasepharmacotherapylink',
            table='disease_pharmaco_therapy_link',
        ),
        migrations.AlterModelTable(
            name='diseasepreventionlink',
            table='disease_prevention_link',
        ),
        migrations.AlterModelTable(
            name='diseaseregimentaltherapylink',
            table='disease_regimental_therapy_link',
        ),
        migrations.AlterModelTable(
            name='diseasesymptomlink',
            table='disease_symptom_link',
        ),
        migrations.AlterModelTable(
            name='diseasetreatmentprinciplelink',
            table='disease_treatment_principle_link',
        ),
        migrations.AlterModelTable(
            name='drug',
            table='drugs',
        ),
        migrations.AlterModelTable(
            name='drugpharmacotherapylink',
            table='drug_pharmaco_therapy_link',
        ),
        migrations.AlterModelTable(
            name='pharmacotherapy',
            table='pharmaco_therapies',
        ),
        migrations.AlterModelTable(
            name='prevention',
            table='preventions',
        ),
        migrations.AlterModelTable(
            name='regimentaltherapy',
            table='regimental_therapies',
        ),
        migrations.AlterModelTable(
            name='symptom',
            table='symptoms',
        ),
        migrations.AlterModelTable(
            name='symptomregimentaltherapylink',
            table='symptom_regimental_therapy_link',
        ),
        migrations.AlterModelTable(
            name='treatmentprinciple',
            table='treatment_principles',
        ),
    ]
