# Generated by Django 4.2.1 on 2023-05-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_icd_code_disease_icode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='name_eng',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='name_eng',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name_persian',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='diseasecauselink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diseasedietlink',
            name='diet_type',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='diseasedietlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diseasedruglink',
            name='drug_dose',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='diseasedruglink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diseasepharmacotherapylink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diseasepreventionlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diseaseregimentaltherapylink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diseasesymptomlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diseasetreatmentprinciplelink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name_eng',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='drugpharmacotherapylink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pharmacotherapy',
            name='name_eng',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='prevention',
            name='name_eng',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='regimentaltherapy',
            name='name_eng',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='name_eng',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='symptomregimentaltherapylink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='treatmentprinciple',
            name='name_eng',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
